export const GET_ALL_RECIPES_REQ = 'GET_ALL_RECIPES_REQ';
export const GET_ALL_RECIPES_SUC = 'GET_ALL_RECIPES_SUC';
export const GET_ALL_RECIPES_FAIL = 'GET_ALL_RECIPES_FAIL';

export const GET_RECIPE_REQ = 'GET_RECIPE_REQ';
export const GET_RECIPE_SUC = 'GET_RECIPE_SUC';
export const GET_RECIPE_FAIL = 'GET_RECIPE_FAIL';

export const GET_ASSET_REQ = 'GET_ASSET_REQ';
export const GET_ASSET_SUC = 'GET_ASSET_SUC';
export const GET_ASSET_FAIL = 'GET_ASSET_FAIL';
